export const TEAMS = [
  {
    id: 1,
    abbreviation: 'ATL',
    city: 'Atlanta',
    conference: 'East',
    division: 'Southeast',
    full_name: 'Atlanta Hawks',
    name: 'Hawks',
    logo: 'https://cdn.nba.com/logos/nba/1610612737/primary/L/logo.svg',
  },
  {
    id: 2,
    abbreviation: 'BOS',
    city: 'Boston',
    conference: 'East',
    division: 'Atlantic',
    full_name: 'Boston Celtics',
    name: 'Celtics',
    logo: 'https://cdn.nba.com/logos/nba/1610612738/primary/L/logo.svg',
  },
  {
    id: 3,
    abbreviation: 'BKN',
    city: 'Brooklyn',
    conference: 'East',
    division: 'Atlantic',
    full_name: 'Brooklyn Nets',
    name: 'Nets',
    logo: 'https://cdn.nba.com/logos/nba/1610612751/primary/L/logo.svg',
  },
  {
    id: 4,
    abbreviation: 'CHA',
    city: 'Charlotte',
    conference: 'East',
    division: 'Southeast',
    full_name: 'Charlotte Hornets',
    name: 'Hornets',
    logo: 'https://cdn.nba.com/logos/nba/1610612766/primary/L/logo.svg',
  },
  {
    id: 5,
    abbreviation: 'CHI',
    city: 'Chicago',
    conference: 'East',
    division: 'Central',
    full_name: 'Chicago Bulls',
    name: 'Bulls',
    logo: 'https://cdn.nba.com/logos/nba/1610612741/primary/L/logo.svg',
  },
  {
    id: 6,
    abbreviation: 'CLE',
    city: 'Cleveland',
    conference: 'East',
    division: 'Central',
    full_name: 'Cleveland Cavaliers',
    name: 'Cavaliers',
    logo: 'https://cdn.nba.com/logos/nba/1610612739/primary/L/logo.svg',
  },
  {
    id: 7,
    abbreviation: 'DAL',
    city: 'Dallas',
    conference: 'West',
    division: 'Southwest',
    full_name: 'Dallas Mavericks',
    name: 'Mavericks',
    logo: 'https://cdn.nba.com/logos/nba/1610612742/primary/L/logo.svg',
  },
  {
    id: 8,
    abbreviation: 'DEN',
    city: 'Denver',
    conference: 'West',
    division: 'Northwest',
    full_name: 'Denver Nuggets',
    name: 'Nuggets',
    logo: 'https://cdn.nba.com/logos/nba/1610612743/primary/L/logo.svg',
  },
  {
    id: 9,
    abbreviation: 'DET',
    city: 'Detroit',
    conference: 'East',
    division: 'Central',
    full_name: 'Detroit Pistons',
    name: 'Pistons',
    logo: 'https://cdn.nba.com/logos/nba/1610612765/primary/L/logo.svg',
  },
  {
    id: 10,
    abbreviation: 'GSW',
    city: 'Golden State',
    conference: 'West',
    division: 'Pacific',
    full_name: 'Golden State Warriors',
    name: 'Warriors',
    logo: 'https://cdn.nba.com/logos/nba/1610612744/primary/L/logo.svg',
  },
  {
    id: 11,
    abbreviation: 'HOU',
    city: 'Houston',
    conference: 'West',
    division: 'Southwest',
    full_name: 'Houston Rockets',
    name: 'Rockets',
    logo: 'https://cdn.nba.com/logos/nba/1610612745/primary/L/logo.svg',
  },
  {
    id: 12,
    abbreviation: 'IND',
    city: 'Indiana',
    conference: 'East',
    division: 'Central',
    full_name: 'Indiana Pacers',
    name: 'Pacers',
    logo: 'https://cdn.nba.com/logos/nba/1610612754/primary/L/logo.svg',
  },
  {
    id: 13,
    abbreviation: 'LAC',
    city: 'LA',
    conference: 'West',
    division: 'Pacific',
    full_name: 'LA Clippers',
    name: 'Clippers',
    logo: 'https://cdn.nba.com/logos/nba/1610612746/primary/L/logo.svg',
  },
  {
    id: 14,
    abbreviation: 'LAL',
    city: 'Los Angeles',
    conference: 'West',
    division: 'Pacific',
    full_name: 'Los Angeles Lakers',
    name: 'Lakers',
    logo: 'https://cdn.nba.com/logos/nba/1610612747/primary/L/logo.svg',
  },
  {
    id: 15,
    abbreviation: 'MEM',
    city: 'Memphis',
    conference: 'West',
    division: 'Southwest',
    full_name: 'Memphis Grizzlies',
    name: 'Grizzlies',
    logo: 'https://cdn.nba.com/logos/nba/1610612763/primary/L/logo.svg',
  },
  {
    id: 16,
    abbreviation: 'MIA',
    city: 'Miami',
    conference: 'East',
    division: 'Southeast',
    full_name: 'Miami Heat',
    name: 'Heat',
    logo: 'https://cdn.nba.com/logos/nba/1610612748/primary/L/logo.svg',
  },
  {
    id: 17,
    abbreviation: 'MIL',
    city: 'Milwaukee',
    conference: 'East',
    division: 'Central',
    full_name: 'Milwaukee Bucks',
    name: 'Bucks',
    logo: 'https://cdn.nba.com/logos/nba/1610612749/primary/L/logo.svg',
  },
  {
    id: 18,
    abbreviation: 'MIN',
    city: 'Minnesota',
    conference: 'West',
    division: 'Northwest',
    full_name: 'Minnesota Timberwolves',
    name: 'Timberwolves',
    logo: 'https://cdn.nba.com/logos/nba/1610612750/primary/L/logo.svg',
  },
  {
    id: 19,
    abbreviation: 'NOP',
    city: 'New Orleans',
    conference: 'West',
    division: 'Southwest',
    full_name: 'New Orleans Pelicans',
    name: 'Pelicans',
    logo: 'https://cdn.nba.com/logos/nba/1610612740/primary/L/logo.svg',
  },
  {
    id: 20,
    abbreviation: 'NYK',
    city: 'New York',
    conference: 'East',
    division: 'Atlantic',
    full_name: 'New York Knicks',
    name: 'Knicks',
    logo: 'https://cdn.nba.com/logos/nba/1610612752/primary/L/logo.svg',
  },
  {
    id: 21,
    abbreviation: 'OKC',
    city: 'Oklahoma City',
    conference: 'West',
    division: 'Northwest',
    full_name: 'Oklahoma City Thunder',
    name: 'Thunder',
    logo: 'https://cdn.nba.com/logos/nba/1610612760/primary/L/logo.svg',
  },
  {
    id: 22,
    abbreviation: 'ORL',
    city: 'Orlando',
    conference: 'East',
    division: 'Southeast',
    full_name: 'Orlando Magic',
    name: 'Magic',
    logo: 'https://cdn.nba.com/logos/nba/1610612753/primary/L/logo.svg',
  },
  {
    id: 23,
    abbreviation: 'PHI',
    city: 'Philadelphia',
    conference: 'East',
    division: 'Atlantic',
    full_name: 'Philadelphia 76ers',
    name: '76ers',
    logo: 'https://cdn.nba.com/logos/nba/1610612755/primary/L/logo.svg',
  },
  {
    id: 24,
    abbreviation: 'PHX',
    city: 'Phoenix',
    conference: 'West',
    division: 'Pacific',
    full_name: 'Phoenix Suns',
    name: 'Suns',
    logo: 'https://cdn.nba.com/logos/nba/1610612756/primary/L/logo.svg',
  },
  {
    id: 25,
    abbreviation: 'POR',
    city: 'Portland',
    conference: 'West',
    division: 'Northwest',
    full_name: 'Portland Trail Blazers',
    name: 'Trail Blazers',
    logo: 'https://cdn.nba.com/logos/nba/1610612757/primary/L/logo.svg',
  },
  {
    id: 26,
    abbreviation: 'SAC',
    city: 'Sacramento',
    conference: 'West',
    division: 'Pacific',
    full_name: 'Sacramento Kings',
    name: 'Kings',
    logo: 'https://cdn.nba.com/logos/nba/1610612758/primary/L/logo.svg',
  },
  {
    id: 27,
    abbreviation: 'SAS',
    city: 'San Antonio',
    conference: 'West',
    division: 'Southwest',
    full_name: 'San Antonio Spurs',
    name: 'Spurs',
    logo: 'https://cdn.nba.com/logos/nba/1610612759/primary/L/logo.svg',
  },
  {
    id: 28,
    abbreviation: 'TOR',
    city: 'Toronto',
    conference: 'East',
    division: 'Atlantic',
    full_name: 'Toronto Raptors',
    name: 'Raptors',
    logo: 'https://cdn.nba.com/logos/nba/1610612761/primary/L/logo.svg',
  },
  {
    id: 29,
    abbreviation: 'UTA',
    city: 'Utah',
    conference: 'West',
    division: 'Northwest',
    full_name: 'Utah Jazz',
    name: 'Jazz',
    logo: 'https://cdn.nba.com/logos/nba/1610612762/primary/L/logo.svg',
  },
  {
    id: 30,
    abbreviation: 'WAS',
    city: 'Washington',
    conference: 'East',
    division: 'Southeast',
    full_name: 'Washington Wizards',
    name: 'Wizards',
    logo: 'https://cdn.nba.com/logos/nba/1610612764/primary/L/logo.svg',
  },
];
